from openai import OpenAI

from app.core.config import settings
from app.services.prompt_library import PROMPT_LIBRARY


client = OpenAI(api_key=settings.openai_api_key)


def generate_code_bundle(prompt: str, context: str, target_language: str) -> dict:
    system_prompt = (
        "You are Sunflower Studio, an expert senior software engineer. "
        "Generate secure, production-grade code. Return concise explanation first then code."
    )

    style_hint = PROMPT_LIBRARY.get(target_language.lower(), PROMPT_LIBRARY["typescript"])

    response = client.responses.create(
        model=settings.openai_model,
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "system", "content": style_hint},
            {"role": "user", "content": f"Context:\n{context}\n\nTask:\n{prompt}"},
        ],
    )
    text = response.output_text

    explanation = "Generated by Sunflower AI."
    code = text
    if "```" in text:
        explanation = text.split("```")[0].strip() or explanation
        parts = text.split("```")
        if len(parts) >= 2:
            code = parts[1]

    return {
        "model": settings.openai_model,
        "explanation": explanation,
        "code": code.strip(),
    }
